<!DOCTYPE html>
<html lang="cs-cz">
        <head>
                <base href="/localhost" />
                <meta charset="UTF-8" />
                <title><?= $titulek ?></title>
                <meta name="description" content="<?= $popis ?>" />
                <meta name="keywords" content="<?= $klicova_slova ?>" />
                <link rel="stylesheet" href="style.css" type="text/css"/>
        </head>

        <body>
                <article>
                        <h1>Moon Sky Overlay</h1>
                </article>

                <footer>
                        <p>&copy Moon Sky Overlay 2017-2018. Web Developed by
                        <a href="http://www.wks.cz" target="_blank">WKS</a>.</p>
                </footer>
        </body>
</html>
